# encoding=utf-8
# Author: Yu-Lun Chiang
# Description: configuration

上市公司_網址 = "https://isin.twse.com.tw/isin/C_public.jsp?strMode=2"
上市公司_起始列 = 2
上市公司_終止列 = 954
上市公司_欄位 = 0

上櫃公司_網址 = "https://isin.twse.com.tw/isin/C_public.jsp?strMode=4"
上櫃公司_起始列 = -804
上櫃公司_終止列 = -15
上櫃公司_欄位 = 0

台灣股市資訊網_基本資料_網址 = "https://goodinfo.tw/StockInfo/BasicInfo.asp"

MEDIA_NAME = {
    "蘋果日報": "appledaily",
    "中國廣播公司": "bcc",
    "數位時代": "bnext",
    "Meet創業小聚": "bnext",
    "中時新聞網": "chinatimes",
    "旺得富": "chinatimes",
    "信傳媒": "cmmedia",
    "中央社": "cna",
    "匯流新聞網": "cnews",
    "工商時報": "ctee",
    "中天新聞": "ctitv",
    "華視新聞": "cts",
    "中視新聞": "ctv",
    "鉅亨網": "cnyes",
    "鉅亨新聞網": "cnyes",
    "DigiTimes": "digitimes",
    "東森財經新聞": "ebc",  # contents got locked
    "大紀元": "epochtimes",
    "年代新聞": "er",
    "ETtoday新聞雲": "ettoday",
    "ETtoday財經雲": "ettoday",
    "民視新聞": "ftv",
    "風向新聞": "kairos",
    "自由時報電子報": "ltn",
    "自由財經": "ltn",
    "鏡週刊": "mirror",
    "MoneyDJ理財網": "moneydj",
    "經濟日報": "moneyudn",
    "民眾新聞網": "mypeoplevol",
    "新頭殼": "newtalk",
    "今日新聞": "nownews",
    "PChome新聞": "pchome",
    "民報": "peoplenews",
    "公視新聞": "pts",
    "中央廣播電臺": "rti",
    "三立新聞": "setn",
    "新浪新聞": "sina",
    "風傳媒": "storm",
    "台灣好新聞": "taiwanhot",
    "芋傳媒": "taronews",
    "科技新報": "technews",
    "財經新報": "technews",
    "關鍵評論網": "thenewslens",
    "台視新聞": "ttv",
    "TVBS": "tvbs",
    "聯合新聞網": "udn",
    "上報": "upmedia",
    "非凡新聞": "ustv",
    "財訊": "wealth",
    "世界新聞網": "worldjournal",
    "Yahoo奇摩新聞": "yahoo",
    "Yahoo奇摩股市": "yahoo",
}

MEDIA_URL = {
    "蘋果日報": "https://tw.appledaily.com",
    "中國廣播公司": "https://www.bcc.com.tw",
    "數位時代": "https://www.bnext.com.tw",
    "Meet創業小聚": "https://meet.bnext.com.tw",
    "中時新聞網": "https://www.chinatimes.com",
    "旺得富": "https://wantrich.chinatimes.com",
    "信傳媒": "https://www.cmmedia.com.tw",
    "中央社": "https://www.cna.com.tw",
    "匯流新聞網": "https://cnews.com.tw",
    "工商時報": "https://ctee.com.tw",
    "中天新聞": "https://gotv.ctitv.com.tw",
    "華視新聞": "https://news.cts.com.tw",
    "中視新聞": "http://new.ctv.com.tw",
    "鉅亨網": "https://m.cnyes.com",
    "鉅亨新聞網": "https://news.cnyes.com",
    "DigiTimes": "https://www.digitimes.com.tw",
    "東森財經新聞": "https://fnc.ebc.net.tw",  # contents got locked
    "大紀元": "https://www.epochtimes.com",
    "年代新聞": "https://www.eracom.com.tw",
    "ETtoday新聞雲": "https://www.ettoday.net",
    "ETtoday財經雲": "https://finance.ettoday.net",
    "民視新聞": "https://www.ftvnews.com.tw",
    "風向新聞": "https://kairos.news",
    "自由時報電子報": "https://news.ltn.com.tw",
    "自由財經": "https://ec.ltn.com.tw",
    "鏡週刊": "https://www.mirrormedia.mg",
    "MoneyDJ理財網": "https://www.moneydj.com",
    "經濟日報": "https://money.udn.com",
    "民眾新聞網": "https://www.mypeoplevol.com",
    "新頭殼": "https://newtalk.tw",
    "今日新聞": "https://www.nownews.com",
    "PChome新聞": "https://news.pchome.com.tw",
    "民報": "https://www.peoplenews.tw",
    "公視新聞": "https://news.pts.org.tw",
    "中央廣播電臺": "https://www.rti.org.tw",
    "三立新聞": "https://www.setn.com",
    "新浪新聞": "https://news.sina.com.tw",
    "風傳媒": "https://www.storm.mg",
    "台灣好新聞": "https://www.taiwanhot.net",
    "芋傳媒": "https://taronews.tw",
    "科技新報": "https://technews.tw",
    "財經新報": "https://finance.technews.tw",
    "關鍵評論網": "https://www.thenewslens.com",
    "台視新聞": "https://news.ttv.com.tw",
    "TVBS": "https://news.tvbs.com.tw",
    "聯合新聞網": "https://udn.com",
    "上報": "https://www.upmedia.mg",
    "非凡新聞": "https://news.ustv.com.tw",
    "財訊": "https://www.wealth.com.tw",
    "世界新聞網": "https://www.worldjournal.com",
    "Yahoo奇摩新聞": "https://tw.news.yahoo.com",
    "Yahoo奇摩股市": "https://tw.stock.yahoo.com",
}
