name: Python CI

on:
  push:
    branches:
      - dev/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install basic dependencies
        run: pip install flake8 pytest pytest-cov pytest-mock

      - uses: actions/cache@v2
        id: cache_pip
        with:
          path: ${{ env.pythonLocation }}/lib/python3.8/site-packages/*
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies (requirements.txt) if no cache_pip
        if: steps.cache_pip.outputs.cache-hit != 'true'
        run: |
          if [ -f requirements.txt ]; then
              pip install -r requirements.txt
          else
              echo "requirements.txt not found !" 
          fi

      - name: Lint with flake8
        run: flake8 .

      - name: Test crawler/media/* with pytest
        run: PYTHONPATH=./ pytest tests/test_crawler_media --log-cli-level=warning --cov=./ --cov-report=term-missing
