name: Python CI

on:
  push:
    branches:
      - dev/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - uses: actions/cache@v2
        id: cache_pip
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('setup.py') }}-${{ hashFiles('requirements_dev.txt') }}

      - name: Install dependencies (requirements_dev.txt) if no cache_pip
        if: steps.cache_pip.outputs.cache-hit != 'true'
        run: |
          if [ -f requirements_dev.txt ]; then
              pip install -r requirements_dev.txt
          else
              echo "requirements_dev.txt not found !" 
          fi

      - name: Lint with flake8
        run: flake8 .

      - name: Test crawler/media/* with pytest
        run: PYTHONPATH=./ pytest tests/test_crawler_media --log-cli-level=warning --cov=./ --cov-report=term-missing
